name: cepromin

services:
  cepromin:
    build:
      context: .
      dockerfile: Dockerfile
    image: cepromin:latest
    container_name: cepromin
    ports:
      - "8080:8080"
    restart: unless-stopped
